"""Binary-bundle, payload, packaging and 1.4.0 scope checks; no game execution."""
from pathlib import Path
import hashlib,json,struct,sys,zipfile,ast
ROOT=Path(__file__).resolve().parents[1]
VERSION=(ROOT/'VERSION').read_text().strip()
archive=Path(sys.argv[1]) if len(sys.argv)>1 else ROOT/('DRIVER_HUD_'+VERSION+'.zip')
checks=[]
def check(name,ok):
    checks.append({'name':name,'pass':bool(ok)})
    if not ok: raise AssertionError(name)
with zipfile.ZipFile(archive) as z:
    check('ZIP CRC',z.testzip() is None)
    names=z.namelist()
    check('unique paths',len(set(names))==len(names))
    check('no path traversal',all(not n.startswith('/') and '..' not in Path(n).parts for n in names))
    required=['manifest.json','README.txt','README_中文.txt','CHANGELOG.txt','FRV_POSITION_说明.txt','driver_hud.cfg']
    check('install/help assets present',all(n in names for n in required))
    check('no script configurator',not any(n.lower().endswith(('.ps1','.cmd','.bat','.exe'))for n in names))
    check('no competing config inside archive','frv_hud_position.txt' not in names and 'frv_hud_position.json' not in names)
    m=json.loads(z.read('manifest.json'))
    check('hotfix manifest GUID',m['Guid']=='4d9e465c-8d42-4be1-91f6-31a8b3e86140')
    check('correct version name',m['Name']=='DRIVER HUD '+VERSION)
    check('Arsenal only deploys CORE',m['Options'][0]['Include']==['CORE'])
    b=z.read('CORE/9ba626afa44a3aa3.patch_0');source=(ROOT/'driver_hud.lua').read_bytes()
    check('192-byte header followed by exact built Lua',b[192:]==source)
    check('both binary lengths',struct.unpack_from('<I',b,160)[0]==len(source)+8 and struct.unpack_from('<I',b,184)[0]==len(source))
    original=bytearray((ROOT/'baseline/9ba626afa44a3aa3.patch_0.header').read_bytes());now=bytearray(b[:192])
    for offset in (160,184):original[offset:offset+4]=b'\0'*4;now[offset:offset+4]=b'\0'*4
    check('all remaining binary header bytes preserved',original==now)
    check('strict UTF8 payload',source.decode('utf-8').encode('utf-8')==source)
    check('runtime version labels',('DRIVER_HUD '+VERSION+' START native_contract=').encode() in source)
    check('no probe telemetry',not any(x in source for x in [b'PROBE_HEARTBEAT',b'NEW_GATLING_GAP',b'TANK_SCHEMA_PROBE']))
    check('bounded combined new weapon cadence',b'a.next_weapon=now+.1' in source and b'a.next_hull=now+.2' in source)
    check('explicit Hull child refs',b'local refs=type(hf)' in source and b'hf[56]' in source)
    tank=(ROOT/'src/tank_runtime.lua').read_text()
    check('new module has no GOID subtraction binding','hid-5' not in tank and 'hid-2' not in tank and 'hid-1' not in tank)
    check('new module has no unknown targeted getter','call(GS.game_object_field,' not in tank)
    check('no world/global discovery in new module','objects_owned_by' not in tank and 'World.units' not in tank)
    check('reload overlay isolated',b'Tank.ring_ids' in source and b'local saved=M.ids;M.ids={}' in source)
    check('TXT hot reload plus migration',b'frv_hud_position.txt' in source and b'Position.next_read=now+2' in source and b'frv_hud_position.json' in source)
    check('configuration is data-only','loadstring' not in (ROOT/'src/position_config.lua').read_text())
    expected=json.loads((ROOT/'evidence/baseline_resources.json').read_text())
    check('material/aux assets byte-identical',all(hashlib.sha256(z.read(n)).hexdigest()==h for n,h in expected.items()))
    check('no DLL/dump/font distribution',not any(n.lower().endswith(('.dll','.ttf','.otf','.dmp','.mem.bin'))for n in names))
    en=z.read('README.txt').decode();zh=z.read('README_中文.txt').decode()
    check('bilingual TXT instructions','frv_hud_position.txt' in en and 'frv_hud_position.txt' in zh and '记事本' in zh and 'Notepad' in en)
    check('previous log documented','driver_hud_previous.log' in en and 'driver_hud_previous.log' in zh)
    check('geometry option retained','geometry_numbers=false' in en and b'geometry_numbers=true' in z.read('driver_hud.cfg'))
    check('unknown/stale reload documented','dotted ring' in en and '最近一次有效读数' in zh)
    check('validation scope limitation present','exhaustive multiplayer/FPS' in en and '完整多人组合' in zh)
    check('stage equals installed files',all((ROOT/'package'/n).read_bytes()==z.read(n) for n in names))
    check('native guard contract retained',b'r4-73374bd4' in source and b'0xF05B12' in source)
    check('per-wheel fault isolation retained',b'data.hp_valid[i]~=false' in source)
    check('third-party credits retained',b'CowboyBingus' in z.read('CREDITS.txt') and b'DDRK1NG' in z.read('CREDITS.txt'))
report={'archive':archive.name,'sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'checks':checks,'total':len(checks),'fails':0}
(ROOT/'evidence/package_validation.json').write_text(json.dumps(report,indent=2)+'\n')
print('RESULT PACKAGE checks=%d fails=0'%len(checks))
